blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question or start a discussion
    url: https://github.com/hydraide/hydraide/issues/new?labels=question
    about: Ask a question by opening a new issue
