name: Contributor Application
description: Apply to become an official HydrAIDE contributor
title: "Contributor Application: <your-name>"
labels: [contributor, onboarding]
body:
  - type: markdown
    attributes:
      value: |
        👋 **Welcome, future contributor!**

        HydrAIDE isn’t just a project — it’s a movement.
        Whether you want to help build SDKs, improve docs, or share feedback, we’re excited to hear from you!

        Please fill out the short form below. You don’t need to be an expert — curiosity and intention matter most.

  - type: input
    id: name
    attributes:
      label: Your name or GitHub handle
      placeholder: "@yourhandle"
    validations:
      required: true

  - type: textarea
    id: languages
    attributes:
      label: What programming languages are you comfortable with?
      placeholder: e.g. Go (advanced), Node.js (intermediate), Python (beginner)
    validations:
      required: true

  - type: textarea
    id: excitement
    attributes:
      label: What excites you about HydrAIDE?
      placeholder: A sentence or two about what made you curious
    validations:
      required: true

  - type: textarea
    id: projects
    attributes:
      label: Any public projects or GitHub repos you’d like to share? (optional)
      placeholder: Paste links if you'd like!

  - type: textarea
    id: whattodo
    attributes:
      label: What would you love to work on first?
      placeholder: SDK development, documentation, examples, etc.

  - type: markdown
    attributes:
      value: |
        🧠 Once you submit this, we’ll review and get back to you soon.

        If accepted, you’ll receive:
        - Access to the private Contributor Kit
        - A dedicated onboarding issue
        - Public recognition in `CONTRIBUTORS.md` 🎉

        Let’s build something legendary. 💥
