name: Docs Improvement
description: Suggest a fix or enhancement to the HydrAIDE documentation
title: "Docs: <brief description>"
labels: [docs]
body:
  - type: markdown
    attributes:
      value: |
        📚 **Let’s make the docs better.**

        Whether you found a typo, missing section, or unclear phrasing — every bit helps.

  - type: input
    id: location
    attributes:
      label: What file or page does this refer to?
      placeholder: e.g. docs/sdk/go.md or indexing.md
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What needs improvement?
      placeholder: Describe the issue — is it unclear, outdated, or missing something?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Do you have a proposed change?
      placeholder: Optional — share your rewrite or example wording if you have it

  - type: dropdown
    id: urgency
    attributes:
      label: How important is this?
      options:
        - Critical – This is actively confusing users
        - High – It impacts contributor experience
        - Medium – Could be better, but not urgent
        - Low – Just a nice polish
