name: CI
on:
  schedule:
    - cron: "0 9 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "8.0.0"
          enable-cache: true

      - name: Install the project
        run: uv tool install pre-commit

      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
