name: Label Needs Review PR

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited]

jobs:
  add-needs-review-label:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Add 'status:needs-review' label
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['status:needs-review']
            });
